name: kind
version: 0.2.0
description:
  A data modeling framework. Easy serialization and observation object graphs. The API is usable
  without code generation. Includes database primitives such as GeoPoint and UUID.
homepage: https://github.com/dint-dev/kind

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fixnum: ^1.0.0
  protobuf: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0