name: kind
version: 0.1.0-nullsafety.0
description:
  An object-mapping and data frame package. Classes Kind and Prop allow you to define data model.
  Frame allows you to query large data sets efficiently.
homepage: https://github.com/dint-dev/kind

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13