name: kind
version: 0.4.0
description:
  An unified data layer framework that enables serialization, persistence, and state observability
  for any Dart class. Code generation is not necessary.
homepage: https://github.com/dint-dev/kind

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  fixnum: ^1.0.0
  protobuf: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0